### ISSUE TITLE
The policy notice can't be dismissed on a website

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/themeisle-companion#728] opened 2022-01-14 15:56 UTC
The policy notice can't be dismissed on a customer's website. I couldn't replicate the issue on Tastewp, however, on this website it can be replicated with multiple browsers.

https://agnote.com/

Once you click on the Accept button the notice disappears then after refreshing the page or navigating to a different one, the policy appears again.

https://secure.helpscout.net/conversation/1756564945/306035/

**Comment by cristian-ungureanu** [comment] 2022-01-19 10:48
@stefan-cotitosu I had a look here and the way we do this is like this: when the user presses the Accept button, we set a cookie named `obfx-policy-consent` with the value `accepted`. Before displaying the notice, we check that cookie. In this specific case, the cookie is not saved. I think there is another plugin installed ( maybe a caching plugin ) that interferes with the policy notice. Maybe it deletes the Cookies or something. You can ask the client to temporarily disable it, see if the problem is resolved, if yes ask him to purge the cache and see if the problem is fixed.

I'm closing this issue as I checked and there's nothing wrong with our module but feel free to reopen it if you find something else.

**Comment by selul** [comment] 2022-05-03 18:49
I've managed to replicate this on optimole.com, seems like if cookies are ignored on the PHP side, i.e $_COOKIE['obfx-policy-consent'] is always empty this never gets hidden

This workflow is very common in a strong cached environment with high traffic. 

My idea to overcome this is to set the default CSS for obfx-cookie-bar as `display:none;`, which seems to fix on optimole.com

**Closed** 2022-05-27 14:29 UTC
Labels: bug
