### ISSUE TITLE
Installing Neve and TPC from OrbitFox > Template Directory leads to wrong page

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#813] opened 2023-10-21 13:47 UTC
### Description

https://vertis.d.pr/v/uQSw8i

### Step-by-step reproduction instructions

1. install OrbitFox
2. go to OrbitFox > Template Directory
3. click on Install & activate TPC
4. click on Install & activate Neve
=> you are redirected to a non-existing page

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment] 2023-10-24 07:06
The link that is currently opened and doesn't work - https://screwwrench.s3-tastewp.com/wp-admin/themes.php?page=tiob-starter-sites

Correct link - https://screwwrench.s3-tastewp.com/wp-admin/admin.php?page=tiob-starter-sites

**Comment by irinelenache** [comment] 2023-10-25 08:16
@girishpanchal30 Tested and the issue is fixed now, thank you 👍

**Closed** 2023-12-18 20:49 UTC
Labels: bug
