### ISSUE TITLE
Updating from 2.10.8 to 2.10.9 breaks site

### ISSUE THREAD

**Issue by stevetasticsteve** [Codeinwp/themeisle-companion#722] opened 2021-12-23 15:10 UTC
Orbit Fox plugin auto-updated to 2.10.9 and our site experienced an internal server error. I could still login to wp-admin and roll back the plugin, which fixed the problem.
The log states:

Warning: require(/usr/www/users/reachk/wp-content/plugins/themeisle-companion/vendor/codeinwp/gutenberg-blocks/inc/css/blocks/class-core-image-plugin-css.php): failed to open stream: No such file or directory in /usr/www/users/reachk/wp-content/plugins/themeisle-companion/vendor/codeinwp/gutenberg-blocks/autoloader.php on line 148

Fatal error: require(): Failed opening required '/usr/www/users/reachk/wp-content/plugins/themeisle-companion/vendor/codeinwp/gutenberg-blocks/inc/css/blocks/class-core-image-plugin-css.php' (include_path='.:/usr/local/lib/php/') in /usr/www/users/reachk/wp-content/plugins/themeisle-companion/vendor/codeinwp/gutenberg-blocks/autoloader.php on line 148

Apologies if that's not all the info needed or if is the wrong place to post. My Php knowledge is essentially nill.

**Comment by cristian-ungureanu** [comment] 2021-12-23 15:16
Checking it right now. Thanks for reporting it!

**Comment by cristian-ungureanu** [comment] 2021-12-23 17:09
@stevetasticsteve I was checking it and I can't reproduce it. Can you help me with a list of plugins that you have active on your website and a screenshot with the activated modules from Orbitfox?

**Comment by stevetasticsteve** [comment] 2021-12-23 17:30
![orbit_fox3](https://user-images.githubusercontent.com/38364294/147274083-26f46134-60cb-44a2-811e-58bcecf2a1a7.png)
![orbit_fox2](https://user-images.githubusercontent.com/38364294/147274086-727ad832-ccd6-4328-b8fc-7d6e9f8968d7.png)
![orbit_fox1](https://user-images.githubusercontent.com/38364294/147274089-040f2297-9ce1-4965-970b-f571a9c88190.png)
![plugins2](https://user-images.githubusercontent.com/38364294/147274091-c372f1c6-6381-4270-8a05-998668b4a38b.png)
![plugins1](https://user-images.githubusercontent.com/38364294/147274092-4e2d5f17-bb65-4de9-b76b-73edb7c32db8.png)

I see a warning about the Gutenberg block module (orbit_fox1.png). Could that be the culprit?

**Comment by stevetasticsteve** [comment] 2021-12-23 17:37
I tried installing  Gutenberg Blocks and Template Library by Otter and am unable to activate it:


Fatal error: Cannot declare class ThemeIsle\GutenbergBlocks\Autoloader, because the name is already in use in /usr/www/users/reachk/wp-content/plugins/otter-blocks/autoloader.php on line 15

**Comment by stevetasticsteve** [comment] 2021-12-23 17:39
Resolved the problem by updating to 2.10.9, disabling the Orbit Fox Gutenberg blocks module and then  Gutenberg Blocks and Template Library by Otter could be activated

**Comment by cristian-ungureanu** [comment] 2021-12-23 18:11
Thanks a lot for reporting this and for all your help. I've released an update that should fix the problem for everyone. Let me know if anything else appears.

**Comment by cristian-ungureanu** [comment] 2022-01-02 21:25
Closing this as the problem was fixed in 2.10.10. Thanks, @stevetasticsteve for reporting this and for all the extra information provided.

**Closed by cristian-ungureanu** 2022-01-02 21:25 UTC
