### ISSUE TITLE
Privacy Modules improvements

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/themeisle-companion#259] opened 2018-06-22 18:20 UTC
When there's no Privacy Policy page is set in the core, there should be a notice in the plugin's Dropdown panel about "You haven't specified...bla bla bla"

**Comment by dascalescuro** [comment] 2018-07-17 10:20
If the user has a different language, the `Agree` button is only translatable from the .pot file
I find it to be a bad experience and we should let the user add his own wording for the button: http://prntscr.com/k7ftn1

Just have the option to change the text of the button.

Thoughts, @andreilupu @selul ?

**Comment by dascalescuro** [comment] 2018-09-21 14:01
We should remove the Agree buton.
I don't think we store the consent and for other languages this is not translated: http://prntscr.com/kx2vnh

**Comment by contactashish13** [comment] 2018-11-20 09:29
@dascalescuro Can I assume #304 is a duplicate of https://github.com/Codeinwp/themeisle-companion/issues/259#issuecomment-405533995 and #306 addresses this?

@HardeepAsrani can you give more detail on https://github.com/Codeinwp/themeisle-companion/issues/259#issue-334973876?

**Comment by dascalescuro** [comment] 2018-11-20 10:30
@contactashish13 I would assume that it is a duplicate should be fine if #306 addresses it :)
thanks!

**Comment by HardeepAsrani** [comment] 2018-11-20 21:48
@contactashish13 When there's no Privacy Policy page set in your WordPress, the module should notify about it. It says it'll display the default Core Privacy Policy but to me it shows nothing.

**Comment by contactashish13** [comment] 2018-12-03 14:10
@selul When there's no Privacy Policy page set in your WordPress, maybe the first option should say `Default Core Policy (Not Set)` instead of `Default Core Policy`. What do you think?

**Comment by selul** [comment] 2018-12-04 07:50
Yes, looking great from my side.

**Comment by contactashish13** [comment] 2018-12-05 07:01
PR: https://github.com/Codeinwp/themeisle-companion/pull/315

**Comment by cristian-ungureanu** [comment] 2021-03-09 10:32
I'm closing this issue, it seems that we already fixed it.

**Closed by cristian-ungureanu** 2021-03-09 10:32 UTC
Labels: enhancement
