### ISSUE TITLE
MyStockPhotos module issue with Gutenberg 

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/themeisle-companion#442] opened 2020-04-01 09:11 UTC
The "Mystock Import" module is not working with Gutenberg. 

I tested with the classic editor and is working properly: https://drive.google.com/file/d/1j5zg_wcEyaraq9BrFA3sHWpFbo3rNvSa/view?usp=sharing

However, when I use Gutenberg this feature no longer appears: https://drive.google.com/file/d/1KbonqikTCks3zCJV5hbqcNG6gAstqJfQ/view?usp=sharing

User message: https://wordpress.org/support/topic/uhm-ok/

**Comment by cristian-ungureanu** [comment] 2020-04-09 08:04
I will close this issue as it's a duplicate of https://github.com/Codeinwp/themeisle-companion/issues/386

**Closed** 2020-04-09 09:27 UTC
