### ISSUE TITLE
Fatal error on eyepatch

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#403] opened 2019-12-03 11:30 UTC
Saw on Neve's PR's that on eyepatch on the frontpage, there's a fatal error coming from OBFX
http://eyepatch.ai/gallery/128498/RVlBS0ZqWkFGTEVWOkVZQVM0SVRFcTFWNG9RV3dDTW0=/

![Screenshot](https://user-images.githubusercontent.com/3266155/70047540-ebb35200-15d0-11ea-98ac-f1ed930ce8e4.png)

**Comment by cristian-ungureanu** [comment] 2019-12-03 14:58
Elementor introduced the ICONS control in version 2.6 and they've launched another 15 updates after that. The problem is that Elementor on eyepatch is older than 2.6.
As I talked with @selul , we need to update Elementor on eyepatch. No need to add backward compatibility with an older version for this.

**Comment by selul** [comment] 2019-12-04 12:14
should be fixed with the upcoming builds

**Closed** 2019-12-04 16:20 UTC
Labels: bug
