### ISSUE TITLE
Compatibility issue Orbit Fox- Elementor Pro

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/themeisle-companion#844] opened 2024-04-15 18:38 UTC
### Description

Users reported incompatibility issues between Orbit Fox and Elementor Pro.

I was not able to replicate it.

### Step-by-step reproduction instructions

1. Install Elementor and Elementor Pro
2. Install Orbit Fox
3. Update WP to the latest version 

### Screenshots, screen recording, code snippet or Help Scout ticket

https://secure.helpscout.net/conversation/2569937337/413766/
![elementor error](https://github.com/Codeinwp/themeisle-companion/assets/86592992/3f0b0d90-f9df-4da5-8e88-5bb566e43105)
[system-info-www.enablersofchange.com.au-15-04-2024.txt](https://github.com/Codeinwp/themeisle-companion/files/14983080/system-info-www.enablersofchange.com.au-15-04-2024.txt)

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by AndreeaCristinaRadacina** [comment] 2024-04-15 18:38
+1 https://secure.helpscout.net/conversation/2570353120/413830?viewId=931544

**Comment by vytisbulkevicius** [comment] 2024-04-15 18:49
@AndreeaCristinaRadacina,

We haven't made a release for 3 weeks, so I wouldn't call this a regression. I see Elementor made a release today and both tickets are submitted today, so it seems like the issue was introduced by Elementor release.

Also, the error is also thrown by Elementor not OrbitFox: 
![image](https://github.com/Codeinwp/themeisle-companion/assets/36594177/648ae934-9c31-4102-b705-7515a6e18776)

@preda-bogdan, can you also take a look when you can to see if it's a problem that should be fixed from our end?

**Comment by preda-bogdan** [comment] 2024-04-16 10:53
@vytisbulkevicius it is caused by https://github.com/Codeinwp/elementor-extra-widgets which is a dependency of OBFX and it will trigger and error inside the new version of Elementor Pro because of this line here:https://github.com/Codeinwp/elementor-extra-widgets/blob/master/class-elementor-extra-widgets.php#L139 this should return the `$data` instead of `NULL` to not crash the editor on the newer versions od Elementor PRO.

**Closed** 2024-04-17 23:25 UTC
Labels: bug, small, customer report, Priority-Medium
