### ISSUE TITLE
Fatal Error on gutenberg-blocks

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/themeisle-companion#354] opened 2019-04-25 12:32 UTC
A few users reported this with the latest version of Orbit Fox.

I was not able to replicate the issue. I have tried activating Otter Blocks too, changing the PHP version, changing both plugins version, used Post Grid and Advanced columns blocks.

### Detailed testing steps:
Blocks used: Post Grid and Advanced columns (Section)

PHP versions:
- 7.2.0
- 7.1.4
- 7.0.3
- 5.6.20
- 5.5.38

Otter versions:
- 1.1.5
- 1.2.0
- 1.2.1

Orbit Fox versions:

- 2.7.5
- 2.8.0
- 2.8.1
- 2.8.2
- 2.8.3

### Errors reported by users and tickets

`Fatal error: Cannot redeclare class ThemeIsle\GutenbergBlocks\Posts_Grid_Block in D:\Home\ApacheRoot\gbddev1\httpdocs\poam\wp-content\plugins\themeisle-companion\vendor\codeinwp\gutenberg-blocks\src\blocks\posts\class-posts-grid-block.php on line 232`
https://secure.helpscout.net/conversation/836850297/187249/

`Fatal error: Cannot redeclare class ThemeIsle\GutenbergBlocks\Posts_Grid_Block in /home/tabasc5/bigpicturetheatre.ca/wp-content/plugins/themeisle-companion/vendor/codeinwp/gutenberg-blocks/src/blocks/posts/class-posts-grid-block.php on line 232 `
https://secure.helpscout.net/conversation/834106825/187007/

`PHP Fatal error: Cannot declare class ThemeIsle\GutenbergBlocks\Posts_Grid_Block, because the name is already in use in /home/mythizyf/public_html/meshology.guru/henry/wp-content/plugins/themeisle-companion/vendor/codeinwp/gutenberg-blocks/src/blocks/posts/class-posts-grid-block.php on line 232`
https://secure.helpscout.net/conversation/834206125/187015/

`Fatal error: Cannot declare class ThemeIsle\GutenbergBlocks\Advanced_Columns_Server, because the name is already in use in /home/tsinet5/public_html/wp-content/plugins/themeisle-companion/vendor/codeinwp/gutenberg-blocks/src/blocks/section/class-advanced-columns-server.php on line 232`
https://secure.helpscout.net/conversation/835978755/187165/

Any help would be much appreciated
cc @HardeepAsrani @contactashish13

**Comment by HardeepAsrani** [comment] 2019-04-25 21:36
@stefan-cotitosu Can you ask them for list of Installed Plugins?

**Comment by stefan-cotitosu** [comment] 2019-04-30 06:48
@HardeepAsrani Sure, I'll do that. Thanks for taking care of this.

**Comment by stefan-cotitosu** [comment] 2019-04-30 13:19
@HardeepAsrani here are the screenshots from one of the users.
Ticket: https://secure.helpscout.net/conversation/834206125/187015/

![Plugin Screen 1](https://user-images.githubusercontent.com/26867648/56964315-9eb35d00-6b63-11e9-8f57-aa106e2836e6.png)
![Plugin Screen 2](https://user-images.githubusercontent.com/26867648/56964326-a246e400-6b63-11e9-953b-21fa85a7e6ca.png)

**Comment by HardeepAsrani** [comment] 2019-05-01 04:16
I still can't reproduce this issue. @stefan-cotitosu Any more info that I can use? Can you ask them for their credentials?

**Comment by stefan-cotitosu** [comment] 2019-05-02 07:51
@HardeepAsrani Another user sent his plugins list
https://secure.helpscout.net/conversation/834106825/187007?folderId=212385

![BPT Screenshot for Stefan@Themeisle 1](https://user-images.githubusercontent.com/26867648/57062187-24501d80-6cc8-11e9-8063-875dab503420.jpg)
![BPT Screenshot for Stefan @ Themeisle 2](https://user-images.githubusercontent.com/26867648/57062195-274b0e00-6cc8-11e9-86f9-cb563754df31.jpg)

**Comment by stefan-cotitosu** [comment] 2019-05-02 07:51
Hardeep, I can ask them for credentials, but if we activate the plugin on their site, it will throw the fatal error again.

**Comment by rodica-andronache** [comment] 2019-05-02 10:39
@HardeepAsrani @stefan-cotitosu saw this one too, not sure if it helps https://wordpress.org/support/topic/fatal-error-cannot-redeclare-class-themeislegutenbergblocks/

**Comment by HardeepAsrani** [comment] 2019-05-03 02:26
@stefan-cotitosu There are no common plugins. It must be caused by something else. :(

I tried but can't reproduce.

**Comment by HardeepAsrani** [comment] 2019-05-03 02:33
@abaicus @selul Any ideas?

**Comment by abaicus** [comment] 2019-05-03 05:47
Maybe get the PHP error log to look at the call stack. My guess is that something isn’t properly required or namespaced.

**Comment by preda-bogdan** [comment] 2019-05-03 06:58
`Cannot declare class ThemeIsle\GutenbergBlocks\Posts_Grid_Block, because the name is already in use in wp-content/plugins/themeisle-companion/vendor/codeinwp/gutenberg-blocks/src/blocks/posts/class-posts-grid-block.php`
It looks like a name collision from vendors

**Comment by selul** [comment] 2019-05-03 07:00
@HardeepAsrani I would show some love to the blocks autoloader, maybe you can use a PSR-4 approach of loading them. 

Moreover, this class name seems bugged for me https://github.com/Codeinwp/gutenberg-blocks/blob/master/class-gutenberg-blocks.php#L263 using two `\\` 

Maybe you can use something like `if (class_exists(ClassName::class)) { ` when checking if the library is already loaded. 

Also, the gutenberg-blocks library action hooks, i.e https://github.com/Codeinwp/gutenberg-blocks/blob/master/class-gutenberg-blocks.php#L1088 should load based on the class check. 

You can also add the 2nd param to class_exists calls to prevent autoload, i.e `class_exists(ClassName::class, true)`

**Comment by preda-bogdan** [comment] 2019-05-03 07:14
@selul  [L263](https://github.com/Codeinwp/gutenberg-blocks/blob/master/class-gutenberg-blocks.php#L263) is not bugged he is just escaping the `\` before `'`
@HardeepAsrani I agree with Marius, maybe do a check before declaring classes if you know you might have more instances of this plugin inside the same wordpress instalation.

**Comment by selul** [comment] 2019-05-03 07:16
@preda-bogdan yes, you're right, my bad.

**Comment by HardeepAsrani** [comment] 2019-05-03 08:01
We disable the module if Otter Blocks is enabled: https://github.com/Codeinwp/themeisle-companion/blob/master/obfx_modules/gutenberg-blocks/init.php#L39

And we also check if the class exists in the main class (which contains our autoloader) before loading it: https://github.com/Codeinwp/gutenberg-blocks/blob/master/class-gutenberg-blocks.php#L5

That shouldn't prevent it? @selul @preda-bogdan

**Comment by selul** [comment] 2019-05-03 08:03
@HardeepAsrani my guess is that otter folder might be renamed in that case which fails the companion check. 

The class check should work I guess 🤔 , maybe you can add the autoload flag too to the function.

**Comment by HardeepAsrani** [comment] 2019-05-03 08:09
@selul I tried changing the name and everything and it still didn't cause any fatal error.

For the class check, can you give more pointers as I've never written an autoloaded before? 👯‍♂

**Comment by preda-bogdan** [comment] 2019-05-03 08:14
As you do here [class-gutenberg-blocks.php#L5](https://github.com/Codeinwp/gutenberg-blocks/blob/master/class-gutenberg-blocks.php#L5) you should do the same here [class-posts-grid-block.php#L7](https://github.com/Codeinwp/gutenberg-blocks/blob/139be1219a8c2bd581875253f363c4c085f86b6c/src/blocks/posts/class-posts-grid-block.php#L7) and in other classes. IMO

**Comment by HardeepAsrani** [comment] 2019-05-03 08:15
Yes, I totally agree with you but that's still not telling us why it's failing now. 😛

**Comment by selul** [comment] 2019-05-03 08:17
@HardeepAsrani by class check i mean to use the 2nd param here `class_exists(ClassName::class, true)`

For autoloader, you can check this guide https://www.php-fig.org/psr/psr-4/ 

Basically, you just need to respect the filename/classname rules, you don't need to write the autoloader as composer is doing that for you, here you have something that we do with Neve to autoload the classes with composer https://github.com/Codeinwp/neve/blob/master/composer.json#L23

**Comment by selul** [comment] 2019-05-03 08:18
@HardeepAsrani my guess is that some edge cases here and until we manage to replicate the issue, we can do those things, at least we will be on the safe side with them.

**Comment by preda-bogdan** [comment] 2019-05-03 08:18
> Yes, I totally agree with you but that's still not telling us why it's failing now.

Because it might already exist as a dependency of another module or plugin.

**Comment by stefan-cotitosu** [comment] 2019-05-09 13:55
@HardeepAsrani Any update on this one? 🙂

**Comment by HardeepAsrani** [comment] 2019-05-09 17:02
@stefan-cotitosu I'll improve the checking in the next version. For now can you ask one user for login and FTP so we could try to debug it, if possible?

**Comment by stefan-cotitosu** [comment] 2019-05-09 17:05
@HardeepAsrani Yes, I will ask. I was hoping that you can implement what Bogdan suggested without other input from users. Then I can ask them to activate the latest version of the plugin, to see if you managed to fix it.

Thanks again for your help with this one. Another user reported the problem today, that's why I asked.

**Comment by stefan-cotitosu** [comment] 2019-05-10 11:57
@HardeepAsrani Another user said the plugin caused a fatal error but he can't provide the error code because the hosting company disabled the plugin.

Fortunately, this is the only user who gave us FTP access so we can debug the issue. Here is the ticket
https://secure.helpscout.net/conversation/849078749/188341?folderId=212385

Thanks for checking this one 🙂

**Comment by HardeepAsrani** [comment] 2019-05-10 20:59
@stefan-cotitosu I'm not sure it's the same issue as they said it's related to PHP version. Also, I'll also need WP login details to test.

**Comment by stefan-cotitosu** [comment] 2019-05-14 07:21
@HardeepAsrani Parrot token in the ticket. Thanks.

**Comment by HardeepAsrani** [comment] 2019-05-14 20:53
@stefan-cotitosu I tried and things just worked. No issues. :(

**Comment by stefan-cotitosu** [comment] 2019-05-19 13:02
@HardeepAsrani Did you activate the plugin on his site and there is no issue?

**Comment by HardeepAsrani** [comment] 2019-05-19 21:20
@stefan-cotitosu Yup. No issues when I tried.

**Comment by stefan-cotitosu** [comment] 2019-05-20 07:24
@HardeepAsrani Ok, thanks, I will update the customer.

**Comment by cristian-ungureanu** [comment] 2021-03-09 10:11
I'm closing this issue because it seems like there were no other reports of this and the issue couldn't be reproduced.

**Closed by cristian-ungureanu** 2021-03-09 10:11 UTC
